// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApdTXfu4UvLI3JeK1x-qSQLEGMcHZGGJs',
    appId: '1:153187819758:web:dec274c4038fb630b393ff',
    messagingSenderId: '153187819758',
    projectId: 'flatmator',
    authDomain: 'flatmator.firebaseapp.com',
    storageBucket: 'flatmator.firebasestorage.app',
    measurementId: 'G-XSKL5TP44M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN6oouzXER71fD3aGiBrR4WH7KbTnd_YI',
    appId: '1:153187819758:android:f38f2a50fc6d5015b393ff',
    messagingSenderId: '153187819758',
    projectId: 'flatmator',
    storageBucket: 'flatmator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpixTIayLwjoK1ckAtMm16UOSjp2OY9nw',
    appId: '1:153187819758:ios:385b1ea6c4e78dfab393ff',
    messagingSenderId: '153187819758',
    projectId: 'flatmator',
    storageBucket: 'flatmator.firebasestorage.app',
    iosBundleId: 'com.example.mvpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpixTIayLwjoK1ckAtMm16UOSjp2OY9nw',
    appId: '1:153187819758:ios:385b1ea6c4e78dfab393ff',
    messagingSenderId: '153187819758',
    projectId: 'flatmator',
    storageBucket: 'flatmator.firebasestorage.app',
    iosBundleId: 'com.example.mvpApp',
  );

}